// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER = 'SET_USER';
export const GET_ACTIVE_USER_DEVICES = 'GET_ACTIVE_USER_DEVICES';
export const GET_INACTIVE_USER_DEVICES = 'GET_INACTIVE_USER_DEVICES';
export const GET_ACTIVE_USER_ADVENTURES = 'GET_ACTIVE_USER_ADVENTURES';
export const GET_INACTIVE_USER_ADVENTURES = 'GET_INACTIVE_USER_ADVENTURES';
// userDevices reducers types
export const LOADING_USER_DEVICES = 'LOADING_USER_DEVICES';
export const GET_USER_DEVICES = 'GET_USER_DEVICES';
export const GET_USER_DEVICE = 'GET_USER_DEVICE';
// userAdventures reducers types
export const LOADING_USER_ADVENTURES = 'LOADING_USERADVENTURES';
export const GET_USER_ADVENTURES = 'GET_USER_ADVENTURES';
export const GET_USER_ADVENTURE = 'GET_USER_ADVENTURE';
// Checkouts reducer types
export const SET_SHIPPING_ADDRESS_CHECKOUT = 'SET_SHIPPING_ADDRESS_CHECKOUT';
export const SET_BILLING_ADDRESS_CHECKOUT = 'SET_BILLING_ADDRESS_CHECKOUT';
export const SET_CREDIT_CARD = 'SET_CREDIT_CARD';
export const LOADING_CHECKOUTS = 'LOADING_CHECKOUTS';
export const POST_CHECKOUT = 'POST_CHECKOUT';
export const GET_CHECKOUTS = 'GET_CHECKOUTS';
export const GET_CHECKOUT = 'GET_CHECKOUT';
// DataSets reducer types
export const LOADING_DATASETS = 'LOADING_DATASETS';
export const POST_DATASET = 'POST_DATASET';
export const GET_DATASETS = 'GET_DATASETS';
export const GET_DATASET = 'GET_DATASET';
// Devices reducer types
export const LOADING_DEVICES = 'LOADING_DEVICES';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICE = 'GET_DEVICE';
export const GET_LIKE_DEVICES = 'GET_LIKE_DEVICES';
export const GET_UNLIKE_DEVICES = 'GET_UNLIKE_DEVICES';
export const POST_DEVICE_COMMENT = 'POST_DEVICE_COMMENT';
// Adventures reducer types
export const LOADING_ADVENTURES = 'LOADING_ADVENTURES';
export const GET_ADVENTURES = 'GET_ADVENTURES';
export const GET_ADVENTURE = 'GET_ADVENTURE';
export const GET_LIKE_ADVENTURES = 'GET_LIKE_ADVENTURES';
export const GET_UNLIKE_ADVENTURES = 'GET_UNLIKE_ADVENTURES';
export const POST_ADVENTURE_COMMENT = 'POST_ADVENTURE_COMMENT';
